.TH Generate document.
.PP
About a document generation is too simple, you need 3 things.
.RS
.IP \(bu 2
bash
.IP \(bu 2
ronn
.RE
.PP
and last thing is an awesome:
.RS
.IP \(bu 2
document (markdown)
.RE
.SH Cooking a document.
.PP
You need to put the document into to this directory and than just execute the script as "gen.sh \-\-document".
